services:
  db:
    image: mysql:9.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data # Persistencia de datos
    restart: always

volumes:
  redis-data:  # Volumen
  mysql_data:  # Volumen